---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    apache:
      default_site_enabled: true # we need this for the tests to work

platforms:
  - name: centos-6.7
    run_list:
    - recipe[yum]
#  - name: ubuntu-12.04
#    run_list:
#    - recipe[apt]
#  - name: ubuntu-14.04
#    run_list:
#    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rackspace_apache_php_test::default]
  - name: default_override
    run_list:
      - recipe[rackspace_apache_php_test::override]
  - name: php55
    run_list:
      - recipe[rackspace_apache_php_test::default]
    attributes:
      rackspace_apache_php:
        php_version: '5.5'
  - name: php55_override
    run_list:
      - recipe[rackspace_apache_php_test::override]
    attributes:
      rackspace_apache_php:
        php_version: '5.5'
  - name: php56
    run_list:
      - recipe[rackspace_apache_php_test::default]
    attributes:
      rackspace_apache_php:
        php_version: '5.6'
  - name: php56_override
    run_list:
      - recipe[rackspace_apache_php_test::override]
    attributes:
      rackspace_apache_php:
        php_version: '5.6'
